apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: {{.Values.metadata.namespace.jmeter}}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{.Values.spec.acme.email}}
    privateKeySecretRef:
      name: letsencrypt-production
    http01: {}