apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
  namespace: {{.Values.metadata.namespace.jmeter}}
spec:
  commonName: drgrafanacn
  secretName: tls-secret-staging
  dnsNames:
  - {{.Values.GrafanaFQDN}}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{.Values.GrafanaFQDN}}
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer