apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jmeter-grafana-ingress
  namespace: {{.Values.metadata.namespace.jmeter}}
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - {{.Values.GrafanaFQDN}}
    secretName: tls-secret-production
  rules:
  - host: {{.Values.GrafanaFQDN}}
    http:
      paths:
      - backend:
          serviceName: jmeter-grafana
          servicePort: 3000
        path: /(.*)