apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  namespace: {{.Values.metadata.namespace.jmeter}}
  labels:
    app: influxdb-jmeter
data:
  influxdb.conf: |
    [meta]
      dir = "/var/lib/influxdb/meta"

    [data]
      dir = "/var/lib/influxdb/data"
      engine = "tsm1"
      wal-dir = "/var/lib/influxdb/wal"

    # Configure the graphite api
    [[graphite]]
    enabled = true
    bind-address = ":2003" # If not set, is actually set to bind-address.
    database = "jmeter"  # store graphite data in this database

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-storage
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: influxdb-jmeter
  labels:
    app: influxdb-jmeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-jmeter
  template:
    metadata:
      labels:
        app: influxdb-jmeter
    spec:
      containers:
        - image: influxdb
          imagePullPolicy: IfNotPresent
          name: influxdb
          volumeMounts:
          - name: config-volume
            mountPath: /etc/influxdb
          - name: azureinflux
            mountPath: /var/lib/influxdb
          ports:
            - containerPort: 8083
              name: influx
            - containerPort: 8086
              name: api
            - containerPort: 2003
              name: graphite
      volumes:
      - name: config-volume
        configMap:
         name: influxdb-config
      - name: azureinflux
        persistentVolumeClaim:
          claimName: influx-storage

---

apiVersion: v1
kind: Service
metadata:
  name: jmeter-influxdb-svc
  labels:
    app: influxdb-jmeter
spec:
   type: ClusterIP
   ports:
    - port: 8083
      name: http
      targetPort: 8083
    - port: 8086
      name: api
      targetPort: 8086
    - port: 2003
      name: graphite
      targetPort: 2003
   selector:
    app: influxdb-jmeter